class_name State

enum Core {WELCOME, LOADING, PLAYING_SOLO, PLAYING_ONLINE, LEAVING, STOPPING_GAME, QUITTING}
enum LaunchMode {CREATION, JOIN}
enum Network {IDLE, CONNECTING, AUTHENTICATING, WAITING_GAMEINFO, CLOSING}
enum Server {NOT_RUNNING, WAITING_PORT, RUNNING}
enum UI {MODAL_SOLO, MODAL_ONLINE, GAME_HUD}
